#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L " ___ _____ __  __  _____ _   _ _____ _____ ___";
$L "| _ \  ___|  \/  ||  ___| \ | |_   _|  ___| _ \  \\";
$L "|| || |__ | .  . || |__ |  \| | | | | |__ || ||";
$L "|| ||  __|| |\/| ||  __|| . | | | | |  __||| ||";
$L "||//| |___| |  | || |___| |\  | | | | |___||//";
$L "|_/ \____/\_|  |_/\____/\_| \_/ \_/ \____/|_/";
$L "Welcome to Android `getprop ro.build.version.release` / DEMENTED-`getprop ro.demented.version`";
