# Versioning of the ROM
PLATFORM_VERSION_CODENAME := UNOFFICIAL
ROM_VERSION := $(PLATFORM_VERSION)-$(shell date +"%m-%d-%y")-$(DEMENTED_RELEASE_TYPE)-$(subst demented_,,$(TARGET_PRODUCT))
DEMENTED_VERSION := $(PLATFORM_VERSION)-$(DEMENTED_RELEASE_TYPE)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.demented.version=$(ROM_VERSION)

