#!/bin/bash

. $ANDROID_BUILD_TOP/vendor/demented/tools/colors

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   MD5=md5sum
   SED=sed
else
   MD5="md5 -r "
   SED=gsed
fi

# manipulate TARGET_PRODUCT to give us just device
BUILD_PROP=${OUT}/system/build.prop
DEVICE=$(cat ${BUILD_PROP} | grep ro.demented.device | cut -d '=' -f2)
demented_DEVICE=$(echo ${TARGET_PRODUCT} | cut -d '_' -f2)

DEVICE_REVISION=$(cat ${BUILD_PROP} | grep ro.demented.version | cut -f2 -d "=")

# Full path to firmware zip package
OUTFILE="demented"-${DEVICE_REVISION}.zip
ZIPSIZE=`ls -lah ${OUT}/${OUTFILE} | awk '{ print $5}' `

# md5sum of zip package
MD5SUM=$(cat ${OUT}/${OUTFILE}.md5sum | cut -d " " -f1)

# Timestamp of build completion extracted from build.prop
TIMESTAMP=$(sed -n -e'/ro\.build\.date\.utc/s/^.*=//p' ${BUILD_PROP})

# Determine the release from the $DEVICE_REVISION
IFS=.
read -a array <<< "$DEVICE_REVISION"
case ${#array[@]} in
    1) CHANNEL=STABLE ;;
    2) CHANNEL=STABLE ;;
    3) CHANNEL=STABLE ;;
    4) CHANNEL=EXPERIMENTAL ;;
esac

MD5=${MD5SUM}
TIMESTAMP=${TIMESTAMP}
CHANNEL=${CHANNEL}
API_LEVEL=${API_LEVEL}
DEVICE=${DEVICE}
SUBDIRECTORY=${demented_DEVICE}

    echo ""
    echo -e ${CL_BLD}""
    echo -e ${CL_INS}"     ___ _____ __  __  _____ _   _ _____ _____ ___    ____  _____  "
    echo -e "    | _ \  ___|  \/  ||  ___| \ | |_   _|  ___| _ \  / ___||  _  |"
    echo -e "    || || |__ | .  . || |__ |  \| | | | | |__ || || / /___ | | | |"
    echo -e "    || ||  __|| |\/| ||  __|| . | | | | |  __||| || | ___ \| | | |"
    echo -e "    ||//| |___| |  | || |___| |\  | | | | |___||//  | \_/ |\ |_/ /"
    echo -e "    |_/ \____/\_|  |_/\____/\_| \_/ \_/ \____/|_/   \_____(_)___/"
    echo ""
    echo ""
echo -e ${CL_INS}${CL_BLD}"  Package Complete:"
echo -e ${CL_MAG}"      ${OUTFILE}"
echo -e ${CL_INS}"  Package Size:"
echo -e ${CL_MAG}"      ${ZIPSIZE}"
echo -e ${CL_INS}"  MD5:"
echo -e ${CL_MAG}"      ${MD5SUM}"
echo -e ${CL_INS}"  Timestamp:"
echo -e ${CL_MAG}"      ${TIMESTAMP}"${CL_RST}
echo -e ""

# NOTE: to use this feature, you also need to get the nma.sh
# shell script from http://storage.locked.io/files/nma.sh
# everything else is pretty self explanatory. The api_key
# file *is* in the .gitignore of this repo, so it will not
# be tracked.
if [[ $USE_NMA = true ]]; then
    api_key=`cat $ANDROID_BUILD_TOP/vendor/demented/tools/api_key`
    priority="0"
    app_name="demented Build Notifier"
    event=`date`
    description="${TARGET_PRODUCT} Build complete!"

    notify-my-android \
                    -k "$api_key" \
                    -p "$priority" \
                    -a "$app_name" \
                    -e "$event" \
                    -d "$description"
fi
